version: '3'
services:
  app:
    container_name: node-docker
    env_file:
      - .env
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=test
    ports:
      - '27017:27017'