version: '3'
services:
  app:
    container_name: node-docker
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - db
  db:
    container_name: mongo-docker
    image: mongo
    ports:
      - '27017:27017'